// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Smart_Route_Planner.Data;

#nullable disable

namespace Smart_Route_Planner.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260422180021_EdgeForeignKeys")]
    partial class EdgeForeignKeys
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Smart_Route_Planner.Models.Apartment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Lat")
                        .HasColumnType("float");

                    b.Property<double>("Lng")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("NodeId")
                        .HasColumnType("bigint");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NodeId");

                    b.ToTable("Apartments");
                });

            modelBuilder.Entity("Smart_Route_Planner.Models.Edge", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<double>("Distance")
                        .HasColumnType("float");

                    b.Property<long>("FromNodeId")
                        .HasColumnType("bigint");

                    b.Property<long>("ToNodeId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("FromNodeId");

                    b.HasIndex("ToNodeId");

                    b.ToTable("Edges");
                });

            modelBuilder.Entity("Smart_Route_Planner.Models.Node", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<double>("Lat")
                        .HasColumnType("float");

                    b.Property<double>("Lng")
                        .HasColumnType("float");

                    b.Property<long>("OsmId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Nodes");
                });

            modelBuilder.Entity("Smart_Route_Planner.Models.Apartment", b =>
                {
                    b.HasOne("Smart_Route_Planner.Models.Node", "Node")
                        .WithMany("Apartments")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Node");
                });

            modelBuilder.Entity("Smart_Route_Planner.Models.Edge", b =>
                {
                    b.HasOne("Smart_Route_Planner.Models.Node", "FromNode")
                        .WithMany("EdgesSources")
                        .HasForeignKey("FromNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Smart_Route_Planner.Models.Node", "ToNode")
                        .WithMany("EdgesDistinations")
                        .HasForeignKey("ToNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromNode");

                    b.Navigation("ToNode");
                });

            modelBuilder.Entity("Smart_Route_Planner.Models.Node", b =>
                {
                    b.Navigation("Apartments");

                    b.Navigation("EdgesDistinations");

                    b.Navigation("EdgesSources");
                });
#pragma warning restore 612, 618
        }
    }
}
